[workspace]

members = [
    "plabayo-news-sendmail",
    "plabayo-news-auth",
    "plabayo-news-api",
    "plabayo-news-builder",
    "plabayo-news-data",
    "plabayo-news-web",
]
default-members = [
    "plabayo-news-web",
]
