[package]
name = "plabayo-news-builder"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
serde = "1"
serde_yaml = "0"
toml = "0"
pulldown-cmark = "0"
convert_case = "0"
