FROM ekidd/rust-musl-builder:stable as build

# set cwd for RUN and CMD
WORKDIR /var/www

# copy files from this directory '.' to '/var/www'
ADD --chown=rust:rust ./plabayo-news-web .
COPY --chown=rust:rust .git .git

RUN cargo build --release

FROM scratch

WORKDIR /var/www

COPY --from=build /var/www/target/x86_64-unknown-linux-musl/release/plabayo-news-web /var/www

EXPOSE 8888

CMD ["./plabayo-news-web"]
