[package]
name = "plabayo-news-web"
version = "0.0.1"
authors = ["Glen De Cauwsemaecker <glen@plabayo.tech>"]
edition = "2021"
build = "./src/build.rs"

[[bin]]
name = "plabayo-news-web"
path = "./src/main.rs"

[package.metadata.i18n]
available-locales = ["en"]
default-locale = "en"
load-path = "./site/locales"

[dependencies]
env_logger = "0"
actix-web = "3"
actix-web-static-files = "3"
static-files = "0"
askama = "0"
anyhow = "1"
fnv = "1"
lazy_static = "1"
rust-i18n = "0"
pulldown-cmark = "0"

[build-dependencies]
actix-web-static-files = "3"
askama = "0"
anyhow = "1"
vergen = { version = "5", default-features = false, features = ["build", "git"] }
